# -*- coding: utf-8 -*-
"""Max_Velocity (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lc8SANWZvlvgaylKewmbnOcJ3ofDyiQ1

**In this colab file I make sure that the **
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# The CSV format is:
# timestamp,quat_w,quat_x,quat_y,quat_z,lat,lon,gps_speed,altitude
df = pd.read_csv(
    "/content/run11 (1).csv",
    header=None,
    names=["timestamp", "quat_w", "quat_x", "quat_y", "quat_z", "lat", "lon", "gps_speed", "altitude"]
)
print(df.head())

#Run 1
max_speed = df['gps_speed'].max()
print("Maximum gps_speed:", max_speed)

#Run 2
max_speed = df['gps_speed'].max()
print("Maximum gps_speed:", max_speed)

#Run 3
max_speed = df['gps_speed'].max()
print("Maximum gps_speed:", max_speed)

#Run 4
max_speed = df['gps_speed'].max()
print("Maximum gps_speed:", max_speed)

#Run 5
max_speed = df['gps_speed'].max()
print("Maximum gps_speed:", max_speed)

#Run 7
max_speed = df['gps_speed'].max()
print("Maximum gps_speed:", max_speed)

#Run 8
max_speed = df['gps_speed'].max()
print("Maximum gps_speed:", max_speed)

#Run 9
max_speed = df['gps_speed'].max()
print("Maximum gps_speed:", max_speed)

#Run 11
max_speed = df['gps_speed'].max()
print("Maximum gps_speed:", max_speed)